ALTER TABLE public.cliente DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.proyecto DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.trabajador DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.contratista DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.registro_trabajo DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."automatizacionWhatsApp" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.catalogo_trabajo DISABLE ROW LEVEL SECURITY;
